2018-03-23T22:53:01.314Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'rahulamin@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)
    at /home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-23T22:53:01.316Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'rahulamin@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'rahulamin@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)\n\n    at _initializeChannel.then.then.then.then.catch (/home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
