2018-03-21T15:58:40.633Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'ankitsbhamra@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)
    at /home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-21T15:58:40.634Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'ankitsbhamra@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'ankitsbhamra@gmail.com' in collection with ID 'Participant:org.cse.piinet.Member' does not exist)\n    at channel.queryByChaincode.then.catch (/home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-03-21T16:14:43.889Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: The specified identity has already been revoked)
    at /home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-21T16:14:43.890Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: The specified identity has already been revoked)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: The specified identity has already been revoked)\n\n    at _initializeChannel.then.then.then.then.catch (/home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-03-21T16:15:53.045Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID '27c582d674ddf0f230854814b7cfd04553f3d0eac55e37d915386c614a5a1de9' in collection with ID 'Asset:org.hyperledger.composer.system.Identity' does not exist)
    at /home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-21T16:15:53.045Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '27c582d674ddf0f230854814b7cfd04553f3d0eac55e37d915386c614a5a1de9' in collection with ID 'Asset:org.hyperledger.composer.system.Identity' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '27c582d674ddf0f230854814b7cfd04553f3d0eac55e37d915386c614a5a1de9' in collection with ID 'Asset:org.hyperledger.composer.system.Identity' does not exist)\n    at channel.queryByChaincode.then.catch (/home/saif/.nvm/versions/node/v8.9.4/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
